DROP TABLE IF EXISTS
mpa,
genre,
films,
film_genre,
users,
likes,
friends;

CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (200) NOT NULL,
    description varchar,
    release_date date,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    genre_id INTEGER REFERENCES genre (id) ON DELETE RESTRICT,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL UNIQUE,
    login varchar NOT NULL UNIQUE,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER UNIQUE REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE

);

